import 'dotenv/config';
import nodemailer from 'nodemailer';

const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
        user: process.env.MAIL_USER,
        pass: process.env.MAIL_PASS
    }
});

const transporterWithRetries = async (mailOptions) => {
    const MAX_RETRIES = 3;
    for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
        try {
            const info = await transporter.sendMail(mailOptions);
            return { mailSent: true, message: "Mail sent successfully!", info: info };
        } catch (error) {
            console.log("retrying..");
            if (attempt === MAX_RETRIES) {
                return { mailSent: false, message: "Maximum attempts reached", error: error.message };
            }
        };
    };
};

function newAdminNotificationTemplate(username, userId, role, timestamp) {
    const t = `<html>
            <head>
                <style>
                    body {font - family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f4f4f7; color: #333; margin: 0; padding: 0; }
                    .container {max - width: 600px; margin: 20px auto; background: #ffffff; border-radius: 8px; overflow: hidden; border: 1px solid #e1e1e1; }
                    .content {padding: 30px; line-height: 1.6; }
                    .badge {background - color: #e8f0fe; color: #1a73e8; padding: 4px 12px; border-radius: 15px; font-weight: bold; font-size: 14px; }
                    .details-box {background - color: #f8f9fa; border-left: 4px solid #1a1a1a; padding: 15px; margin: 20px 0; }
                    .footer {background - color: #f1f1f1; color: #777; text-align: center; padding: 15px; font-size: 12px; }
                    .warning {color: #d93025; font-size: 13px; margin-top: 10px; font-style: italic; }
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="content">
                        <p>Dear User,</p>
                        <p>This is an automated notification to inform that your <strong>administrator account</strong> has been successfully generated in the system.</p>

                        <div class="details-box">
                            <strong>New User Details:</strong><br>
                                Name: ${username}<br>
                                    User Id: ${userId}<br>
                                        Role: <span class="badge">${role}</span><br>
                                            Generated At: ${timestamp}
                                        </div>

                                        <p>If this action was expected, no further steps are required. However, if you do not recognize this activity, please contact authorised person.</p>

                                        <p class="warning">Note: New administrators have high-level access to the school database and user management features.</p>
                                    </div>
                                    <div class="footer">
                                        &copy; 2026 School Management System | Security Operations
                                    </div>
                                </div>
                            </body>
                        </html>`
    return t;
}

/**
 * @param {string} username 
 * @param {string} userId 
 * @param {string} role 
 * @param {string} timestamp 
 * @param {string} recipient 
 * @returns {null} Notifies the provided user about his new account that was created on the system.
 */

export const generateNewAdminNotification = async (username, userId, role, timestamp, recipient) => {
    let template = newAdminNotificationTemplate(username, userId, role, timestamp);
    const mailOptions = {
        from: "autogenerated",
        to: recipient,
        subject: "Security notification: Account generated!",
        html: template
    }
    const success = await transporterWithRetries(mailOptions);
    if (!success.mailSent) {
        console.log("unable to send mail:", success.error)
    } else {
        console.log("Notified user:", success.info.messageId);
    };
};